### ISSUE TITLE
FastBuild-Dashboard crashed at startup when configured to start when windows starts

### ISSUE THREAD

**Issue by jspelletier** [hillin/FASTBuilder#1]
title is explanatory. For now I have disabled the option but I could probably reproduce it and give you a crash dump if you need to.

JS

**Comment by hillin** [comment]
Thanks for reporting. This issue is fixed with https://github.com/hillin/FASTBuild-Dashboard/commit/ca13816eb42c531c503f27963a21b0682659e4ac. The [latest release](https://github.com/hillin/FASTBuild-Dashboard/releases/tag/0.93.3) also contains this fix.
