### ISSUE TITLE
wrong package path in FASTBuild.Dashboard.csproj?

### ISSUE THREAD

**Issue by Domain** [hillin/FASTBuilder#10]
I cannot build FASTBuild.Dashboard using VS2017. I have to replace all "..\packages\" to "packages\" in FASTBuild.Dashboard.csproj to build the project.

**Comment by hillin** [comment]
Yes, it seems I have both folders existed with all third-party libs. I've corrected this with https://github.com/hillin/FASTBuild-Dashboard/commit/0f9e99036e5a289912f908299a3431911965acb4.
