### ISSUE TITLE
Shadow directory

### ISSUE THREAD

**Issue by jspelletier** [hillin/FASTBuilder#3]
Hi,

Could you modify the shadow behavior so that the shadow is done in the Temp directory instead of the current directory ?

The reason is that we put tools in Perforce and build machines are at least once per 24h doing a cleanup pass to remove all files not in perforce(clean build). With the current behavior if FastBuild-Dashboard is running the cleanup will fail.

Thanks

**Comment by hillin** [comment]
Yes, it's better to spawn the shadow executable in temp folder. It's changed in https://github.com/hillin/FASTBuild-Dashboard/commit/5ae536afc97143f40a514430a0d1266ab7ea29bb.

**Comment by hillin** [comment]
This change is shipped with the [latest release](https://github.com/hillin/FASTBuild-Dashboard/releases/tag/0.93.4).
