### ISSUE TITLE
Provide more information

### ISSUE THREAD

**Issue by Domain** [hillin/FASTBuilder#6]
I want to know more information about the build, such as how many local build, remote build, and timeout.

**Comment by hillin** [comment]
The information requested is possible to be collected and presented, but I don't think they are most relevant to the user's interest while building is in progress. I'm thinking of making a summary screen which sums up all the information, along with data and graphs of other aspects such as CPU time and network throughput - this requests more information to be exposed from FASTBuild though.

**Comment by hillin** [comment]
I'm out of the fastbuild for quite a while now, and I don't see I will be pushing this project forward in the foreseeable future, I'm closing this issue as not planned.
