### ISSUE TITLE
Cannot jump to error when building in remote worker

### ISSUE THREAD

**Issue by Domain** [hillin/FASTBuilder#7]
No error message to click when the file compiled in remote worker

**Comment by hillin** [comment]
Could you please provide a `FastBuildLog.log` file which reflects this issue?

**Comment by Domain** [comment]
I know what happen.  There is no error message in FastBuildLog.log when compiling in remote worker.

**Comment by hillin** [comment]
Yes that's possible, we should fire a feature request to FASTBuild.

**Comment by hillin** [comment]
I've submitted a pull request(https://github.com/fastbuild/fastbuild/pull/288) to FASTBuild to solve this issue.

**Comment by hillin** [comment]
https://github.com/fastbuild/fastbuild/pull/288 has been integrated. This will take effect in the next FASTBuild release (v0.96).
